FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock.json ./

COPY . .

# Utilise ts-node-dev pour recompiler automatiquement
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]
