import { getTokenValue } from "./getTokenValue";

export const buttons = {
  primary: {
      backgroundColor: "var(--app-primary, " + getTokenValue("primary-background") + ")",
      color: getTokenValue("primary-text"),
      fontFamily: "Manrope, sans-serif",
      width: "100%",
      height: "48px",
      fontWeight: "bold",
      fontSize: "16px",
      lineHeight: "24px",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
      transition: "all 0.2s ease",
    },
    secondary: {
      backgroundColor: getTokenValue("secondary-background"),
      color: getTokenValue("secondary-text"),
      fontFamily: "Manrope, sans-serif",
      fontWeight: "bold",
      fontSize: "16px",
      padding: "12px 20px",
      borderRadius: "8px",
      border: `1px solid ${getTokenValue("secondary-border")}`,
      cursor: "pointer",
      maxWidth: "322px",
    },
    tertiary: {
      backgroundColor: getTokenValue("tertiary-background"),
      color: getTokenValue("tertiary-text"),
      fontFamily: "Manrope, sans-serif",
      fontWeight: "bold",
      fontSize: "16px",
      width: "100%",
      textAlign: "center",
      border: "none",
      cursor: "pointer",
    },
    submitButton: {
      padding: "12px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "8px",
      backgroundColor: getTokenValue("primary-background"),
      color: getTokenValue("primary-text"),
      border: "none",
      borderRadius: "16px",
      cursor: "pointer",
      fontWeight: "500",
      marginTop: "8px",
      height: "48px",
      fontSize: "15px",
      letterSpacing: "0.5px",
      hover: {
        opacity: "0.9",
      },
    },
    oAuthButton: {
      flex: 1,
      border: `1px solid ${getTokenValue("secondary-border")} !important`,
      backgroundColor: `${getTokenValue("secondary-background")} !important`,
      color: `${getTokenValue("secondary-text")} !important`,
      fontWeight: "500",
      borderRadius: "16px !important",
      height: "45px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "0 16px !important",
      gap: "8px",
      fontSize: "14px",
      letterSpacing: "0.5px",
    },

  oAuthButton3: {
    flex: "1 1 0",
    height: "56px",
    borderRadius: "28px",
    border: `1px solid ${getTokenValue("secondary-border")}`,
    backgroundColor: getTokenValue("secondary-background"),
    color: getTokenValue("secondary-text"),
    fontWeight: "500",
    fontSize: "16px",
    textTransform: "uppercase",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    cursor: "pointer",
    padding: "0 24px",
    boxSizing: "border-box",
    width: "100%",
    maxWidth: "100%",
    "@media (maxWidth: 768px)": {
      height: "44px",
      borderRadius: "24px",
      fontSize: "14px",
      padding: "0 16px",
      gap: "8px"
    }
  },

  oAuthButton2: {
    flex: "1 1 0",
    height: "56px",
    borderRadius: "28px",
    border: `1px solid ${getTokenValue("secondary-border")}`,
    backgroundColor: getTokenValue("secondary-background"),
    color: getTokenValue("secondary-text"),
    fontWeight: "500",
    fontSize: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    cursor: "pointer",
    padding: "0 24px",
    boxSizing: "border-box",
    width: "100%",
    maxWidth: "100%",
    boxShadow: `0 1px 2px getTokenValue("shadow-medium")`,
    hover: {
      backgroundColor: getTokenValue("secondary-background-hover"),
    }
},
};
